# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gitdoc}
  s.version = "3.10.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Myles Byrne"]
  s.date = %q{2011-03-30}
  s.default_executable = %q{gitdoc}
  s.email = %q{myles@myles.id.au}
  s.executables = ["gitdoc"]
  s.extra_rdoc_files = [
    "README.md",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "TODO",
     "VERSION",
     "bin/gitdoc",
     "default.sass",
     "doc.haml",
     "favicon.ico",
     "gitdoc.rb",
     "gitdoc/tasks.rb",
     "highlight.css",
     "reset.sass"
  ]
  s.homepage = %q{http://github.com/quackingduck/gitdoc}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["."]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A light-weight web app for serving up a folder of markdown files}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rdiscount>, ["~> 1.5.8"])
      s.add_runtime_dependency(%q<haml>, ["~> 3.0.25"])
      s.add_runtime_dependency(%q<sinatra>, ["~> 1.0"])
      s.add_runtime_dependency(%q<unicorn>, ["~> 3.1.0"])
      s.add_runtime_dependency(%q<coffee-script>, ["~> 2.1.1"])
      s.add_runtime_dependency(%q<json>, ["~> 1.4.6"])
      s.add_runtime_dependency(%q<livereload>, ["~> 1.6"])
    else
      s.add_dependency(%q<rdiscount>, ["~> 1.5.8"])
      s.add_dependency(%q<haml>, ["~> 3.0.25"])
      s.add_dependency(%q<sinatra>, ["~> 1.0"])
      s.add_dependency(%q<unicorn>, ["~> 3.1.0"])
      s.add_dependency(%q<coffee-script>, ["~> 2.1.1"])
      s.add_dependency(%q<json>, ["~> 1.4.6"])
      s.add_dependency(%q<livereload>, ["~> 1.6"])
    end
  else
    s.add_dependency(%q<rdiscount>, ["~> 1.5.8"])
    s.add_dependency(%q<haml>, ["~> 3.0.25"])
    s.add_dependency(%q<sinatra>, ["~> 1.0"])
    s.add_dependency(%q<unicorn>, ["~> 3.1.0"])
    s.add_dependency(%q<coffee-script>, ["~> 2.1.1"])
    s.add_dependency(%q<json>, ["~> 1.4.6"])
    s.add_dependency(%q<livereload>, ["~> 1.6"])
  end
end

